volumes:

  dba:
    name: suap-dba
    driver: local
    driver_opts:
      type: none
      device: $HOME/.opt/suap/dba
      o: bind

  red:
    name: suap-red
    driver: local
    driver_opts:
      type: none
      device: $HOME/.opt/suap/red
      o: bind

  sql:
    name: suap-sql
    driver: local
    driver_opts:
      type: none
      device: $HOME/.opt/suap/sql
      o: bind
