volumes:

  dba:
    name: suap-dba
    driver: local
    driver_opts:
      type: none
      device: /opt/suap/2/dba
      o: bind

  red:
    name: suap-red
    driver: local
    driver_opts:
      type: none
      device: /opt/suap/2/red
      o: bind

  sql:
    name: suap-sql
    driver: local
    driver_opts:
      type: none
      device: /opt/suap/2/sql
      o: bind
