version: "3.4"

services:

  app:
    hostname: app
    container_name: suap-app
    build:
      context: .
      dockerfile: Dockerfile
    image: ifmt/suap-app
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8022:8022"
    networks:
      - net
    depends_on:
      - dba
      - red
      - sql

  dba:
    hostname: dba
    container_name: suap-dba
    image: dpage/pgadmin4:5.6
    restart: unless-stopped
    volumes:
      - dba:/var/lib/pgadmin
    ports:
      - "8080:80"
      - "8081:443"
    networks:
      - net
    env_file:
      - .env-dba

  red:
    hostname: red
    container_name: suap-red
    image: bitnami/redis:4.0.9
    restart: unless-stopped
    volumes:
      - red:/bitnami/redis/data
    ports:
      - "6379:6379"
    networks:
      - net
    env_file:
      - .env-red

  sql:
    hostname: sql
    container_name: suap-sql
    image: bitnami/postgresql:12
    restart: unless-stopped
    volumes:
      - sql:/bitnami/postgresql
    ports:
      - "5432:5432"
    networks:
      - net
    env_file:
      - .env-sql

networks:

  net:
    name: suap-net
    driver: bridge
