version: "3.4"

services:

  app:
    hostname: app
    container_name: suap-app
    build:
      context: .
      dockerfile: Dockerfile
    image: ifmt/suap-app
    ports:
      - "8000:8000"

networks:

  default:
    external:
      name: suap-net
