volumes:

  dba:
    name: suap-dba
    driver: local
    driver_opts:
      type: none
      device: ../data/dba
      o: bind

  red:
    name: suap-red
    driver: local
    driver_opts:
      type: none
      device: ../data/red
      o: bind

  sql:
    name: suap-sql
    driver: local
    driver_opts:
      type: none
      device: ../data/sql
      o: bind
