version: "3.4"

services:

  ssh:
    hostname: ssh
    container_name: suap-ssh
    build:
      context: .
      dockerfile: Dockerfile.ssh
    image: ifmt/suap-ssh
    restart: unless-stopped
    volumes:
      - ssh_app:/opt/suap/app
      - ssh_env:/opt/suap/env
    ports:
      - "8022:22"
      - "8080:8000"
    networks:
      - net
    depends_on:
      - dba
      - red
      - sql

  dba:
    hostname: dba
    container_name: suap-dba
    image: dpage/pgadmin4:5.6
    restart: unless-stopped
    volumes:
      - dba:/var/lib/pgadmin
    ports:
      - "8480:80"
      - "8443:443"
    networks:
      - net
    env_file:
      - .env-dba

  red:
    hostname: red
    container_name: suap-red
    image: bitnami/redis:4.0.9
    restart: unless-stopped
    volumes:
      - red:/bitnami/redis/data
    ports:
      - "6379:6379"
    networks:
      - net
    env_file:
      - .env-red

  sql:
    hostname: sql
    container_name: suap-sql
    image: bitnami/postgresql:12
    restart: unless-stopped
    volumes:
      - sql:/bitnami/postgresql
    ports:
      - "5432:5432"
    networks:
      - net
    env_file:
      - .env-sql

networks:

  net:
    name: suap-net
    driver: bridge

volumes:

  ssh_app:
    name: suap-ssh-app
    driver: local
    driver_opts:
      type: none
      device: ../suap
      o: bind

  ssh_env:
    name: suap-ssh-env
    driver: local
    driver_opts:
      type: none
      device: ./env
      o: bind
