version: "3.8"

services:

  app:
    hostname: app
    container_name: suap-app
    build:
      context: .
      dockerfile: Dockerfile
    image: ifmt/suap-app
    restart: unless-stopped
    volumes:
      - app_src:/app/suap
      - app_con:/app/.config
      - app_loc:/app/.local
      - app_ssh:/app/.ssh
    ports:
      - '8000:8000'
      - '8022:22'
      - '8080:8080'
    networks:
      - net
    env_file:
      - .env-dba
    depends_on:
      - dba
      - red
      - sql

  sql:
    hostname: sql
    container_name: suap-sql
    image: bitnami/postgresql:12
    restart: unless-stopped
    volumes:
      - sql:/bitnami/postgresql
    ports:
      - '5432:5432'
    networks:
      - net
    env_file:
      - .env-sql

  red:
    hostname: red
    container_name: suap-red
    image: bitnami/redis:6.2.7
    restart: unless-stopped
    volumes:
      - red:/bitnami/redis
    ports:
      - '6379:6379'
    networks:
      - net
    env_file:
      - .env-red
    profiles:
      - redis

  dba:
    hostname: dba
    container_name: suap-dba
    image: dpage/pgadmin4:6.13
    restart: unless-stopped
    volumes:
      - dba:/var/lib/pgadmin
    ports:
      - '8480:80'
      - '8481:443'
    networks:
      - net
    env_file:
      - .env-dba
    profiles:
      - pgadmin

  moo:
    hostname: moo
    container_name: suap-moo
    image: bitnami/moodle:3.11.9
    restart: unless-stopped
    volumes:
      - moo:/bitnami/moodle
    ports:
      - '8180:8080'
      - '8181:8443'
    networks:
      - net
    env_file:
      - .env-moo
    profiles:
      - moodle

networks:

  net:
    name: suap-net
    driver: bridge

volumes:

  app_src:
    name: suap-app-src
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/../suap
      o: bind

  app_con:
    name: suap-app-con
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/var/con
      o: bind

  app_loc:
    name: suap-app-loc
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/var/loc
      o: bind

  app_ssh:
    name: suap-app-ssh
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/var/ssh
      o: bind

  sql:
    name: suap-sql
    driver: local
    driver_opts:
      type: none
      device: ${BASE}/sql
      o: bind

  red:
    name: suap-red
    driver: local
    driver_opts:
      type: none
      device: ${BASE}/red
      o: bind

  dba:
    name: suap-dba
    driver: local
    driver_opts:
      type: none
      device: ${BASE}/dba
      o: bind

  moo:
    name: suap-moo
    driver: local
    driver_opts:
      type: none
      device: ${BASE}/moo
      o: bind
