version: "3"

services:

  dba:
    image: bitnami/phppgadmin:7.13.0
    env_file:
      - .env-dba
    volumes:
      - dba:/bitnami
    ports:
      - "7080:8080"
      - "7443:8443"
    networks:
      - app

  lda:
    image: bitnami/openldap:2
    env_file:
      - .env-lda
    volumes:
      - lda:/bitnami/openldap
    networks:
      - app

  red:
    image: bitnami/redis:4.0.9
    env_file:
      - .env-red
    volumes:
      - red:/bitnami/redis/data
    networks:
      - app

  sql:
    image: bitnami/postgresql:12
    env_file:
      - .env-sql
    volumes:
      - sql:/bitnami/postgresql
    networks:
      - app

  app:
    build: .
    volumes:
      - app:/app
    ports:
      - "8000:8000"
      - "8022:22"
    networks:
      - app
    depends_on:
      - dba
      - lda
      - red
      - sql

networks:

  app:
    driver: bridge

volumes:

  app:
    driver_opts:
      type: none
      device: ../suap
      o: bind

  dba:
    driver_opts:
      type: none
      device: /opt/suap/dba
      o: bind

  lda:
    driver_opts:
      type: none
      device: /opt/suap/lda
      o: bind

  red:
    driver_opts:
      type: none
      device: /opt/suap/red
      o: bind

  sql:
    driver_opts:
      type: none
      device: /opt/suap/sql
      o: bind
