version: "3.8"

services:

  app:
    hostname: app
    container_name: suap-app
    build:
      context: .
      dockerfile: Dockerfile
    image: ifmt/suap-app
    restart: unless-stopped
    volumes:
      - app_app:/opt/suap/app
      - app_env:/opt/suap/app/.env
      - app_con:/opt/suap/.config
      - app_loc:/opt/suap/.local
    ports:
      - '8000:8000'
      - '8022:22'
      - '8080:8080'
    networks:
      - net
    env_file:
      - .env-dba
    depends_on:
      - dba
      - red
      - sql

  dba:
    hostname: dba
    container_name: suap-dba
    image: dpage/pgadmin4:6.8
    restart: unless-stopped
    volumes:
      - dba:/var/lib/pgadmin
    ports:
      - '8443:443'
      - '8480:80'
    networks:
      - net
    env_file:
      - .env-dba

  red:
    hostname: red
    container_name: suap-red
    image: bitnami/redis:6.0.16
    restart: unless-stopped
    volumes:
      - red:/bitnami/redis/data
    ports:
      - '6379:6379'
    networks:
      - net
    env_file:
      - .env-red

  sql:
    hostname: sql
    container_name: suap-sql
    image: bitnami/postgresql:12
    restart: unless-stopped
    volumes:
      - sql:/bitnami/postgresql
    ports:
      - 5432:5432
    networks:
      - net
    env_file:
      - .env-sql

networks:

  net:
    name: suap-net
    driver: bridge

volumes:

  app_app:
    name: suap-app-app
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/../suap
      o: bind

  app_env:
    name: suap-app-env
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/env
      o: bind

  app_con:
    name: suap-app-con
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/vol/con
      o: bind

  app_loc:
    name: suap-app-loc
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/vol/loc
      o: bind

  dba:
    name: suap-dba
    driver: local
    driver_opts:
      type: none
      device: ${BASE}/dba
      o: bind

  red:
    name: suap-red
    driver: local
    driver_opts:
      type: none
      device: ${BASE}/red
      o: bind

  sql:
    name: suap-sql
    driver: local
    driver_opts:
      type: none
      device: ${BASE}/sql
      o: bind
