version: "3.4"

services:

  dba:
    image: dpage/pgadmin4
    env_file:
      - .env-dba
    volumes:
      - dba:/var/lib/pgadmin
    ports:
      - "8080:80"
    networks:
      - app

  lda:
    image: bitnami/openldap:2
    env_file:
      - .env-lda
    volumes:
      - lda:/bitnami/openldap
    networks:
      - app

  red:
    image: bitnami/redis:4.0.9
    env_file:
      - .env-red
    volumes:
      - red:/bitnami/redis/data
    networks:
      - app

  sql:
    image: bitnami/postgresql:12
    env_file:
      - .env-sql
    volumes:
      - sql:/bitnami/postgresql
    ports:
      - "5432:5432"
    networks:
      - app

  app:
    build: .
    volumes:
      - app:/app
    ports:
      - "8000:8000"
      - "8022:22"
    networks:
      - app
    depends_on:
      - dba
      - lda
      - red
      - sql

networks:

  app:
    driver: bridge
