version: "3"

services:
  sql:
    image: postgres:buster
    env_file:
      - .env-sql
    volumes:
      - sql:/var/lib/postgresql/data
    networks:
      - suap-network
    ports:
      - "8032:5432"

  dba:
    image: dpage/pgadmin4
    env_file:
      - .env-dba
    volumes:
      - dba:/var/lib/pgadmin
    networks:
      - suap-network
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - sql

  app:
    build: .
    volumes:
      - ./src:/workspace
    networks:
      - suap-network
    ports:
      - "8022:22"
    depends_on:
      - sql

networks:
  suap-network:

volumes:
  sql:
    driver: local

  dba:
    driver: local
