version: "3"

services:

  dba:
    image: bitnami/phppgadmin:7.13.0
    env_file:
      - .env-dba
    volumes:
      - dba:/bitnami
    ports:
      - "7080:8080"
      - "7443:8443"
    networks:
      - suap-network

  lda:
    image: bitnami/openldap:2
    env_file:
      - .env-lda
    volumes:
      - lda:/bitnami/openldap
    networks:
      - suap-network

  sql:
    image: bitnami/postgresql:12
    env_file:
      - .env-sql
    volumes:
      - sql:/bitnami/postgresql
    networks:
      - suap-network

  app:
    build: .
    volumes:
      - app:/workspace
    ports:
      - "8000:8000"
      - "8022:22"
    networks:
      - suap-network
    depends_on:
      - lda
      - sql
      - dba

networks:

  suap-network:
    driver: bridge

volumes:

  app:
    driver_opts: 
      type: none
      device: $PWD/src
      o: bind

  dba:
    driver_opts: 
      type: none
      device: /opt/suap/dba
      o: bind

  lda:
    driver_opts: 
      type: none
      device: /opt/suap/lda
      o: bind

  sql:
    driver_opts: 
      type: none
      device: /opt/suap/sql
      o: bind
