version: "3.4"

services:

  app:
    hostname: app
    container_name: suap_app
    build: .
    restart: unless-stopped
    volumes:
      - app:/opt/suap/app
      - opt:/opt/suap
    ports:
      - "8000:8000"
      - "8022:22"
    networks:
      - app
    depends_on:
      - dba
      - lda
      - red
      - sql

  dba:
    hostname: dba
    container_name: suap_dba
    image: dpage/pgadmin4
    restart: unless-stopped
    volumes:
      - dba:/var/lib/pgadmin
    ports:
      - "8080:80"
    networks:
      - app
    env_file:
      - .env-dba

  lda:
    hostname: lda
    container_name: suap_lda
    image: bitnami/openldap:2
    restart: unless-stopped
    volumes:
      - lda:/bitnami/openldap
    networks:
      - app
    env_file:
      - .env-lda

  red:
    hostname: red
    container_name: suap_red
    image: bitnami/redis:4.0.9
    restart: unless-stopped
    volumes:
      - red:/bitnami/redis/data
    networks:
      - app
    env_file:
      - .env-red

  sql:
    hostname: sql
    container_name: suap_sql
    image: bitnami/postgresql:12
    restart: unless-stopped
    volumes:
      - sql:/bitnami/postgresql
    ports:
      - "5432:5432"
    networks:
      - app
    env_file:
      - .env-sql

networks:

  app:
    driver: bridge

volumes:

  app:
    driver: local
    driver_opts:
      type: none
      device: ../suap
      o: bind

  opt:
    driver: local
    driver_opts:
      type: none
      device: ./opt
      o: bind
